application: eat-right
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6
- name: pycrypto
  version: 2.6
- name: lxml
  version: 2.3

handlers:
- url: /assets
  static_dir: assets
  
- url: /sitemap.xml
  static_files: sitemap.xml
  upload: /sitemap.xml
  
- url: /robots.txt
  static_files: robots.txt
  upload: /robots.txt

- url: /.*
  script: eatright.application
